sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
install: npm install
before_script:
  - npm install
  - npm run test
script: npm run build
after_success:
  - npx semantic-release
branches:
only: master