sudo: false
language: node_js
cache: yarn
notifications:
  email: false
node_js: '10'
install: yarn install
before_script:
  - yarn install
  - yarn run test
script: yarn run build
after_success:
  - npx semantic-release
branches:
  only:
    - master